# Generated by Django 6.0.6 on 2026-07-02 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_master_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='stage',
            field=models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
        migrations.AddField(
            model_name='trial',
            name='bought_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trial',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_trials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trial',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
