# Generated by Django 6.0.6 on 2026-07-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_chatmessage_is_deleted_client_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiosettings',
            name='default_price_ab4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studiosettings',
            name='default_price_ab8',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studiosettings',
            name='default_price_master_class',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studiosettings',
            name='default_price_trial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
