# Generated by Django 6.0.6 on 2026-07-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_studiosettings_default_price_ab4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
