# Generated by Django 6.0.6 on 2026-07-02 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_trial_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='direction',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='client',
            name='parent_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='client',
            name='school_class',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='finance_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_class_payment', to='crm.financetransaction'),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='finance_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payment', to='crm.financetransaction'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='finance_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_payment', to='crm.financetransaction'),
        ),
        migrations.AddField(
            model_name='visit',
            name='lesson_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('attended', 'Attended'), ('missed', 'Missed'), ('makeup', 'Makeup'), ('frozen', 'Frozen'), ('trial', 'Trial'), ('planned', 'Planned'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
    ]
