# Generated by Django 6.0.6 on 2026-07-05 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_room_subject_lesson_visit_lesson_scheduleslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_groups', to='crm.room'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='schedule_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
