# Generated by Django 6.0.6 on 2026-07-05 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_studygroup_end_time_studygroup_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_trials', to='crm.subscription'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('import', 'Import'), ('payment', 'Payment'), ('visit', 'Visit'), ('task_done', 'Task done'), ('password_change', 'Password change'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('trial_converted_to_subscription', 'Trial converted to subscription')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trial',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='crm.client'),
        ),
    ]
