# Generated by Django 6.0.6 on 2026-07-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_catalogitem_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('attended', 'Attended'), ('sick', 'Sick'), ('missed', 'Missed'), ('makeup', 'Makeup'), ('frozen', 'Frozen'), ('trial', 'Trial'), ('planned', 'Planned'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
    ]
