# Generated by Django 6.0.6 on 2026-07-09 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_visit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('import', 'Import'), ('payment', 'Payment'), ('visit', 'Visit'), ('task_done', 'Task done'), ('password_change', 'Password change'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('trial_converted_to_subscription', 'Trial converted to subscription'), ('catalog_item_create', 'Catalog item create'), ('catalog_item_update', 'Catalog item update'), ('catalog_item_disable', 'Catalog item disable'), ('branch_create', 'Branch create'), ('branch_update', 'Branch update'), ('branch_disable', 'Branch disable')], max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='crm.branch'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='crm.branch'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='crm.branch'),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_classes', to='crm.branch'),
        ),
        migrations.AddField(
            model_name='room',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='crm.branch'),
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_slots', to='crm.branch'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_groups', to='crm.branch'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='crm.branch'),
        ),
        migrations.AddField(
            model_name='task',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.branch'),
        ),
        migrations.AddField(
            model_name='trial',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trials', to='crm.branch'),
        ),
        migrations.AddField(
            model_name='visit',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='crm.branch'),
        ),
    ]
