# Generated by Django 6.0.6 on 2026-07-09 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_branch_alter_auditlog_action_client_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='lessons_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='service',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='crm.catalogitem'),
        ),
    ]
