# Generated by Django 6.0.6 on 2026-07-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_catalogitem_lessons_count_subscription_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='validity_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
