# Generated by Django 6.0.6 on 2026-07-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_catalogitem_validity_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='schedule_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
