# Generated by Django 6.0.6 on 2026-07-11 08:03

import django.db.models.deletion
from django.db import migrations, models


def move_extra_services_to_addons(apps, schema_editor):
    CatalogItem = apps.get_model('crm', 'CatalogItem')
    CatalogItem.objects.filter(category='extra_service').update(category='addon')


def move_addons_to_extra_services(apps, schema_editor):
    CatalogItem = apps.get_model('crm', 'CatalogItem')
    CatalogItem.objects.filter(category='addon').update(category='extra_service')


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_catalogitem_schedule_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='category',
            field=models.CharField(choices=[('service', 'Услуги'), ('product', 'Товары'), ('addon', 'Доп. услуги'), ('extra_service', 'Доп. услуги')], max_length=30),
        ),
        migrations.CreateModel(
            name='SubscriptionAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_item', models.ForeignKey(limit_choices_to={'category': 'addon'}, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_addons', to='crm.catalogitem')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_addons', to='crm.subscription')),
            ],
            options={
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('subscription', 'catalog_item'), name='unique_subscription_addon_item')],
            },
        ),
        migrations.RunPython(move_extra_services_to_addons, move_addons_to_extra_services),
    ]
