# Generated by Django 6.0.6 on 2026-07-13 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_alter_auditlog_action_addonsale_addonsaleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonsale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='addonsale',
            name='discount_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='addonsale',
            name='discount_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='addonsale',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='discount_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='discount_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='discount_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('import', 'Import'), ('payment', 'Payment'), ('visit', 'Visit'), ('task_done', 'Task done'), ('password_change', 'Password change'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('trial_converted_to_subscription', 'Trial converted to subscription'), ('catalog_item_create', 'Catalog item create'), ('catalog_item_update', 'Catalog item update'), ('catalog_item_disable', 'Catalog item disable'), ('branch_create', 'Branch create'), ('branch_update', 'Branch update'), ('branch_disable', 'Branch disable'), ('payment_method_create', 'Payment method create'), ('payment_method_update', 'Payment method update'), ('payment_method_disable', 'Payment method disable'), ('payment_method_enable', 'Payment method enable'), ('discount_create', 'Discount create'), ('discount_update', 'Discount update'), ('discount_disable', 'Discount disable'), ('discount_enable', 'Discount enable'), ('group_update', 'Group update'), ('group_disable', 'Group disable'), ('group_enable', 'Group enable'), ('group_member_add', 'Group member add'), ('group_member_remove', 'Group member remove'), ('group_member_restore', 'Group member restore'), ('addon_sale_create', 'Addon sale create'), ('addon_sale_update', 'Addon sale update')], max_length=50),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='crm.branch')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='addonsale',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addon_sales', to='crm.discount'),
        ),
        migrations.AddField(
            model_name='financetransaction',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to='crm.discount'),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_classes', to='crm.discount'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='crm.discount'),
        ),
    ]
