# Generated by Django 6.0.6 on 2026-07-21 17:22

from django.db import migrations, models


def mark_camp_services(apps, schema_editor):
    CatalogItem = apps.get_model('crm', 'CatalogItem')
    for item in CatalogItem.objects.filter(category='service').iterator():
        name = (item.name or '').casefold()
        if '\u043b\u0430\u0433\u0435\u0440\u044c' in name or 'camp' in name:
            item.service_type = 'camp'
            item.save(update_fields=('service_type',))


def unmark_camp_services(apps, schema_editor):
    CatalogItem = apps.get_model('crm', 'CatalogItem')
    CatalogItem.objects.filter(service_type='camp').update(service_type='course')


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_addonsale_discount_amount_addonsale_discount_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='service_type',
            field=models.CharField(choices=[('course', 'Course'), ('camp', 'Camp')], default='course', max_length=20),
        ),
        migrations.RunPython(mark_camp_services, unmark_camp_services),
    ]
