# Generated by Django 6.0.6 on 2026-07-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_camp_subscription_finance_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonsale',
            name='discount_value',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='discount_value',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='discount_value',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
