# Generated by Django 6.0.6 on 2026-07-21 21:00

import django.db.models.deletion
from django.db import migrations, models


def create_parts_for_existing_transactions(apps, schema_editor):
    FinanceTransaction = apps.get_model('crm', 'FinanceTransaction')
    FinancePaymentPart = apps.get_model('crm', 'FinancePaymentPart')
    for transaction in FinanceTransaction.objects.filter(payment_method__isnull=False, amount__gt=0).iterator():
        if FinancePaymentPart.objects.filter(transaction_id=transaction.id, payment_method_id=transaction.payment_method_id).exists():
            continue
        FinancePaymentPart.objects.create(
            transaction_id=transaction.id,
            payment_method_id=transaction.payment_method_id,
            payment_method_name=transaction.payment_method_name or transaction.payment_method.name,
            amount=transaction.amount,
        )


def remove_created_parts(apps, schema_editor):
    FinancePaymentPart = apps.get_model('crm', 'FinancePaymentPart')
    FinancePaymentPart.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_paymentmethod_is_cash_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancePaymentPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_payment_parts', to='crm.paymentmethod')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_parts', to='crm.financetransaction')),
            ],
            options={
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('transaction', 'payment_method'), name='unique_payment_method_per_transaction')],
            },
        ),
        migrations.RunPython(create_parts_for_existing_transactions, remove_created_parts),
    ]
