# Generated by Django 6.0.6 on 2026-07-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_financepaymentpart'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='financepaymentpart',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_payment_part_amount_positive'),
        ),
    ]
