# Generated by Django 6.0.6 on 2026-07-21 21:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_financepaymentpart_finance_payment_part_amount_positive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount_type', models.CharField(choices=[('fixed', '?????????????'), ('range', '????????')], default='fixed', max_length=20)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('validity_days', models.PositiveIntegerField(default=365)),
                ('sale_discount_percent', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('background_from', models.CharField(default='#fff7ed', max_length=20)),
                ('background_to', models.CharField(default='#fef3c7', max_length=20)),
                ('accent_color', models.CharField(default='#f59e0b', max_length=20)),
                ('text_color', models.CharField(default='#1f2937', max_length=20)),
                ('badge_text', models.CharField(blank=True, default='?????????? ??????????', max_length=100)),
                ('terms', models.TextField(blank=True)),
                ('background_image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-is_active', 'name'),
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('import', 'Import'), ('payment', 'Payment'), ('visit', 'Visit'), ('task_done', 'Task done'), ('password_change', 'Password change'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('trial_converted_to_subscription', 'Trial converted to subscription'), ('catalog_item_create', 'Catalog item create'), ('catalog_item_update', 'Catalog item update'), ('catalog_item_disable', 'Catalog item disable'), ('branch_create', 'Branch create'), ('branch_update', 'Branch update'), ('branch_disable', 'Branch disable'), ('payment_method_create', 'Payment method create'), ('payment_method_update', 'Payment method update'), ('payment_method_disable', 'Payment method disable'), ('payment_method_enable', 'Payment method enable'), ('discount_create', 'Discount create'), ('discount_update', 'Discount update'), ('discount_disable', 'Discount disable'), ('discount_enable', 'Discount enable'), ('group_update', 'Group update'), ('group_disable', 'Group disable'), ('group_enable', 'Group enable'), ('group_member_add', 'Group member add'), ('group_member_remove', 'Group member remove'), ('group_member_restore', 'Group member restore'), ('addon_sale_create', 'Addon sale create'), ('addon_sale_update', 'Addon sale update'), ('cash_reconciliation', 'Cash reconciliation'), ('certificate_template_create', 'Certificate template create'), ('certificate_template_update', 'Certificate template update'), ('certificate_template_disable', 'Certificate template disable'), ('certificate_create', 'Certificate create'), ('certificate_update', 'Certificate update'), ('certificate_redeem', 'Certificate redeem'), ('certificate_cancel', 'Certificate cancel'), ('certificate_whatsapp_open', 'Certificate WhatsApp open')], max_length=50),
        ),
        migrations.CreateModel(
            name='GiftCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_name', models.CharField(blank=True, max_length=150)),
                ('template_snapshot', models.JSONField(blank=True, default=dict)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_phone', models.CharField(blank=True, max_length=30)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_discount_percent', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issued_at', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('partially_used', 'Partially used'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=30)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_phone', models.CharField(blank=True, max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certificates', to=settings.AUTH_USER_MODEL)),
                ('finance_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='crm.financetransaction')),
                ('purchaser_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_certificates', to='crm.client')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='crm.certificatetemplate')),
            ],
            options={
                'ordering': ('-issued_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CertificateRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.TextField(blank=True)),
                ('redeemed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_redemptions', to=settings.AUTH_USER_MODEL)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='crm.giftcertificate')),
            ],
            options={
                'ordering': ('-redeemed_at', '-created_at'),
            },
        ),
    ]
