# Generated by Django 6.0.6 on 2026-07-29 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def assign_certificate_serials(apps, schema_editor):
    GiftCertificate = apps.get_model('crm', 'GiftCertificate')
    CertificateNumberSequence = apps.get_model('crm', 'CertificateNumberSequence')
    current = GiftCertificate.objects.exclude(serial_number__isnull=True).order_by('-serial_number').values_list('serial_number', flat=True).first() or 0
    next_number = int(current) + 1
    for certificate in GiftCertificate.objects.filter(serial_number__isnull=True).order_by('created_at', 'id'):
        certificate.serial_number = next_number
        certificate.save(update_fields=('serial_number',))
        next_number += 1
    CertificateNumberSequence.objects.update_or_create(pk=1, defaults={'last_number': next_number - 1})


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_certificatetemplate_alter_auditlog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateNumberSequence',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('last_number', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='certificateredemption',
            name='remaining_amount_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='certificateredemption',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='certificateredemption',
            name='visitor_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='certificateredemption',
            name='visitor_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='serial_number',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.RunPython(assign_certificate_serials, noop_reverse),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('import', 'Import'), ('payment', 'Payment'), ('visit', 'Visit'), ('task_done', 'Task done'), ('password_change', 'Password change'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('trial_converted_to_subscription', 'Trial converted to subscription'), ('catalog_item_create', 'Catalog item create'), ('catalog_item_update', 'Catalog item update'), ('catalog_item_disable', 'Catalog item disable'), ('branch_create', 'Branch create'), ('branch_update', 'Branch update'), ('branch_disable', 'Branch disable'), ('payment_method_create', 'Payment method create'), ('payment_method_update', 'Payment method update'), ('payment_method_disable', 'Payment method disable'), ('payment_method_enable', 'Payment method enable'), ('discount_create', 'Discount create'), ('discount_update', 'Discount update'), ('discount_disable', 'Discount disable'), ('discount_enable', 'Discount enable'), ('group_update', 'Group update'), ('group_disable', 'Group disable'), ('group_enable', 'Group enable'), ('group_member_add', 'Group member add'), ('group_member_remove', 'Group member remove'), ('group_member_restore', 'Group member restore'), ('addon_sale_create', 'Addon sale create'), ('addon_sale_update', 'Addon sale update'), ('cash_reconciliation', 'Cash reconciliation'), ('certificate_template_create', 'Certificate template create'), ('certificate_template_update', 'Certificate template update'), ('certificate_template_disable', 'Certificate template disable'), ('certificate_create', 'Certificate create'), ('certificate_update', 'Certificate update'), ('certificate_redeem', 'Certificate redeem'), ('certificate_cancel', 'Certificate cancel'), ('certificate_whatsapp_open', 'Certificate WhatsApp open'), ('certificate_batch_create', 'Certificate batch create'), ('certificate_asset_upload', 'Certificate asset upload'), ('certificate_visit_create', 'Certificate visit create')], max_length=50),
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.CreateModel(
            name='CertificateBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchaser_name', models.CharField(blank=True, max_length=150)),
                ('purchaser_phone', models.CharField(blank=True, max_length=30)),
                ('purchaser_phone_snapshot', models.CharField(blank=True, max_length=30)),
                ('template_name', models.CharField(max_length=150)),
                ('template_snapshot', models.JSONField(blank=True, default=dict)),
                ('quantity', models.PositiveIntegerField()),
                ('face_value_per_certificate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_price_per_certificate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_face_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issued_at', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certificate_batches', to=settings.AUTH_USER_MODEL)),
                ('finance_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_batch', to='crm.financetransaction')),
                ('purchaser_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_batches', to='crm.client')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='crm.certificatetemplate')),
            ],
            options={
                'ordering': ('-issued_at', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='crm.certificatebatch'),
        ),
        migrations.CreateModel(
            name='CertificateDesignAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('file_data', models.BinaryField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_design_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='background_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='crm.certificatedesignasset'),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='background_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='crm.certificatedesignasset'),
        ),
    ]
