# Generated by Django 6.0.6 on 2026-07-30 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_certificatenumbersequence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=20)),
                ('event_key', models.CharField(max_length=255, unique=True)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('import', 'Import'), ('payment', 'Payment'), ('visit', 'Visit'), ('task_done', 'Task done'), ('password_change', 'Password change'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('trial_converted_to_subscription', 'Trial converted to subscription'), ('catalog_item_create', 'Catalog item create'), ('catalog_item_update', 'Catalog item update'), ('catalog_item_disable', 'Catalog item disable'), ('branch_create', 'Branch create'), ('branch_update', 'Branch update'), ('branch_disable', 'Branch disable'), ('payment_method_create', 'Payment method create'), ('payment_method_update', 'Payment method update'), ('payment_method_disable', 'Payment method disable'), ('payment_method_enable', 'Payment method enable'), ('discount_create', 'Discount create'), ('discount_update', 'Discount update'), ('discount_disable', 'Discount disable'), ('discount_enable', 'Discount enable'), ('group_update', 'Group update'), ('group_disable', 'Group disable'), ('group_enable', 'Group enable'), ('group_member_add', 'Group member add'), ('group_member_remove', 'Group member remove'), ('group_member_restore', 'Group member restore'), ('addon_sale_create', 'Addon sale create'), ('addon_sale_update', 'Addon sale update'), ('cash_reconciliation', 'Cash reconciliation'), ('certificate_template_create', 'Certificate template create'), ('certificate_template_update', 'Certificate template update'), ('certificate_template_disable', 'Certificate template disable'), ('certificate_create', 'Certificate create'), ('certificate_update', 'Certificate update'), ('certificate_redeem', 'Certificate redeem'), ('certificate_cancel', 'Certificate cancel'), ('certificate_whatsapp_open', 'Certificate WhatsApp open'), ('certificate_batch_create', 'Certificate batch create'), ('certificate_asset_upload', 'Certificate asset upload'), ('certificate_visit_create', 'Certificate visit create'), ('messaging_channel_create', 'Messaging channel create'), ('messaging_channel_update', 'Messaging channel update'), ('lead_created_from_message', 'Lead created from message'), ('lead_status_update', 'Lead status update'), ('lead_assign', 'Lead assign'), ('lead_link_client', 'Lead link client'), ('lead_create_client', 'Lead create client'), ('lead_convert_to_trial', 'Lead convert to trial'), ('lead_mark_read', 'Lead mark read'), ('meta_webhook_error', 'Meta webhook error')], max_length=50),
        ),
        migrations.CreateModel(
            name='MessagingChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('external_account_id', models.CharField(db_index=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('last_webhook_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_channels', to='crm.branch')),
                ('default_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_messaging_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('provider', 'name'),
                'unique_together': {('provider', 'external_account_id')},
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('manual', 'Вручную')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('qualified', 'Квалифицирован'), ('trial_booked', 'Записан на пробник'), ('won', 'Продажа'), ('lost', 'Не купил'), ('spam', 'Спам')], default='new', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_username', models.CharField(blank=True, max_length=255)),
                ('first_message', models.TextField(blank=True)),
                ('last_message', models.TextField(blank=True)),
                ('first_message_at', models.DateTimeField()),
                ('last_message_at', models.DateTimeField()),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.branch')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.client')),
                ('converted_trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='crm.trial')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_leads', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.messagingchannel')),
            ],
            options={
                'ordering': ('-last_message_at',),
            },
        ),
        migrations.CreateModel(
            name='MessagingContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_contact_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('profile_picture_url', models.URLField(blank=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.messagingchannel')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messaging_contacts', to='crm.client')),
            ],
            options={
                'ordering': ('-last_message_at', '-created_at'),
                'unique_together': {('channel', 'external_contact_id')},
            },
        ),
        migrations.CreateModel(
            name='LeadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('inbound', 'Входящее'), ('outbound', 'Исходящее')], max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('video', 'Видео'), ('audio', 'Аудио'), ('document', 'Документ'), ('sticker', 'Стикер'), ('interactive', 'Интерактивное'), ('unknown', 'Другое')], default='text', max_length=30)),
                ('external_message_id', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField(blank=True)),
                ('media_id', models.CharField(blank=True, max_length=255)),
                ('media_url', models.URLField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.lead')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='crm.messagingcontact')),
            ],
            options={
                'ordering': ('sent_at', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.messagingcontact'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='crm_lead_status_2c1bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='crm_lead_source_0cf4cf_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['manager'], name='crm_lead_manager_38ee69_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['last_message_at'], name='crm_lead_last_me_408d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['contact_phone'], name='crm_lead_contact_5e7858_idx'),
        ),
    ]
