# Generated by Django 6.0.6 on 2026-08-27 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_finance_manager(apps, schema_editor):
    FinanceTransaction = apps.get_model('crm', 'FinanceTransaction')
    User = apps.get_model('users', 'User')

    manager_user_ids = []
    for user in User.objects.all().only('id', 'role', 'roles', 'is_superuser'):
        roles = []
        if user.is_superuser:
            roles.append('admin')
        if isinstance(user.roles, list):
            roles.extend(user.roles)
        if user.role:
            roles.append(user.role)
        if 'manager' in set(filter(None, roles)):
            manager_user_ids.append(user.id)

    for transaction in FinanceTransaction.objects.select_related('client', 'created_by').all():
        manager_id = None
        master_class = getattr(transaction, 'master_class_payment', None)
        trial = getattr(transaction, 'trial_payment', None)
        if master_class and master_class.manager_id:
            manager_id = master_class.manager_id
        elif trial and trial.manager_id:
            manager_id = trial.manager_id
        elif transaction.client_id and transaction.client.manager_id:
            manager_id = transaction.client.manager_id
        elif transaction.created_by_id in manager_user_ids:
            manager_id = transaction.created_by_id
        if manager_id:
            transaction.manager_id = manager_id
            transaction.save(update_fields=('manager',))


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_metawebhookevent_alter_auditlog_action_and_more'),
        ('users', '0004_user_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financetransaction',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_finance_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_finance_manager, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('import', 'Import'), ('payment', 'Payment'), ('visit', 'Visit'), ('task_done', 'Task done'), ('password_change', 'Password change'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('trial_converted_to_subscription', 'Trial converted to subscription'), ('catalog_item_create', 'Catalog item create'), ('catalog_item_update', 'Catalog item update'), ('catalog_item_disable', 'Catalog item disable'), ('branch_create', 'Branch create'), ('branch_update', 'Branch update'), ('branch_disable', 'Branch disable'), ('payment_method_create', 'Payment method create'), ('payment_method_update', 'Payment method update'), ('payment_method_disable', 'Payment method disable'), ('payment_method_enable', 'Payment method enable'), ('discount_create', 'Discount create'), ('discount_update', 'Discount update'), ('discount_disable', 'Discount disable'), ('discount_enable', 'Discount enable'), ('group_update', 'Group update'), ('group_disable', 'Group disable'), ('group_enable', 'Group enable'), ('group_member_add', 'Group member add'), ('group_member_remove', 'Group member remove'), ('group_member_restore', 'Group member restore'), ('addon_sale_create', 'Addon sale create'), ('addon_sale_update', 'Addon sale update'), ('cash_reconciliation', 'Cash reconciliation'), ('employee_schedule_create', 'Employee schedule create'), ('employee_schedule_update', 'Employee schedule update'), ('payroll_profile_update', 'Payroll profile update'), ('payroll_generate', 'Payroll generate'), ('payroll_recalculate', 'Payroll recalculate'), ('payroll_adjust', 'Payroll adjust'), ('payroll_approve', 'Payroll approve'), ('payroll_paid', 'Payroll paid'), ('finance_manager_update', 'Finance manager update'), ('master_class_duration_update', 'Master class duration update'), ('certificate_template_create', 'Certificate template create'), ('certificate_template_update', 'Certificate template update'), ('certificate_template_disable', 'Certificate template disable'), ('certificate_create', 'Certificate create'), ('certificate_update', 'Certificate update'), ('certificate_redeem', 'Certificate redeem'), ('certificate_cancel', 'Certificate cancel'), ('certificate_whatsapp_open', 'Certificate WhatsApp open'), ('certificate_batch_create', 'Certificate batch create'), ('certificate_asset_upload', 'Certificate asset upload'), ('certificate_visit_create', 'Certificate visit create'), ('messaging_channel_create', 'Messaging channel create'), ('messaging_channel_update', 'Messaging channel update'), ('lead_created_from_message', 'Lead created from message'), ('lead_status_update', 'Lead status update'), ('lead_assign', 'Lead assign'), ('lead_link_client', 'Lead link client'), ('lead_create_client', 'Lead create client'), ('lead_convert_to_trial', 'Lead convert to trial'), ('lead_mark_read', 'Lead mark read'), ('meta_webhook_error', 'Meta webhook error')], max_length=50),
        ),
        migrations.CreateModel(
            name='EmployeePayrollProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pay_type', models.CharField(choices=[('hourly', 'Почасовая'), ('monthly', 'Оклад')], default='hourly', max_length=20)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('regular_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('outside_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('outside_master_class_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_working_day', models.BooleanField(default=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_work_schedules', to='crm.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('employee', 'weekday', '-valid_from'),
            },
        ),
        migrations.CreateModel(
            name='PayrollStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('pay_type_snapshot', models.CharField(default='hourly', max_length=20)),
                ('monthly_salary_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('regular_hourly_rate_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('outside_hourly_rate_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('outside_master_class_bonus_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('regular_minutes', models.PositiveIntegerField(default=0)),
                ('outside_minutes', models.PositiveIntegerField(default=0)),
                ('outside_master_class_count', models.PositiveIntegerField(default=0)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('regular_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outside_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('master_class_bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('manual_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('manual_adjustment_comment', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_statements', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_statements', to='crm.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_statements', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_statements', to=settings.AUTH_USER_MODEL)),
                ('finance_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_statement', to='crm.financetransaction')),
            ],
            options={
                'ordering': ('-date_to', 'employee'),
                'constraints': [models.UniqueConstraint(fields=('employee', 'date_from', 'date_to'), name='unique_payroll_statement_period')],
            },
        ),
    ]
