# Generated by Django 6.0.6 on 2026-08-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_financetransaction_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='is_extra_work',
            field=models.BooleanField(default=False),
        ),
    ]
