# Generated by Django 6.0.6 on 2026-09-07 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_lead_assignments(apps, schema_editor):
    MasterClass = apps.get_model('crm', 'MasterClass')
    MasterClassStaffAssignment = apps.get_model('crm', 'MasterClassStaffAssignment')
    for master_class in MasterClass.objects.exclude(teacher_id__isnull=True).iterator():
        MasterClassStaffAssignment.objects.get_or_create(
            master_class_id=master_class.id,
            employee_id=master_class.teacher_id,
            defaults={
                'role': 'lead',
                'is_extra_work': master_class.is_extra_work,
                'duration_minutes': None,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_masterclass_is_extra_work'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterClassStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('lead', 'Основной мастер'), ('assistant', 'Помощник')], default='assistant', max_length=20)),
                ('is_extra_work', models.BooleanField(default=False)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_class_staff_assignments', to=settings.AUTH_USER_MODEL)),
                ('master_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='crm.masterclass')),
            ],
            options={
                'ordering': ('master_class', 'role', 'employee'),
                'constraints': [models.UniqueConstraint(fields=('master_class', 'employee'), name='unique_master_class_staff_employee'), models.UniqueConstraint(condition=models.Q(('role', 'lead')), fields=('master_class',), name='unique_master_class_lead_staff')],
            },
        ),
        migrations.RunPython(create_lead_assignments, noop_reverse),
    ]
