# Generated by Django 6.0.6 on 2026-09-10 13:39

from datetime import datetime, time
from decimal import Decimal, ROUND_HALF_UP
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


MONEY = Decimal('0.01')


def money(value):
    return Decimal(value or 0).quantize(MONEY, rounding=ROUND_HALF_UP)


def local_date(value):
    if not value:
        return None
    return django.utils.timezone.localtime(value).date() if django.utils.timezone.is_aware(value) else value.date()


def paid_at_from_date(value):
    return django.utils.timezone.make_aware(datetime.combine(value, time.min))


def migrate_master_class_payments(apps, schema_editor):
    MasterClass = apps.get_model('crm', 'MasterClass')
    MasterClassPayment = apps.get_model('crm', 'MasterClassPayment')
    FinanceTransaction = apps.get_model('crm', 'FinanceTransaction')

    for master_class in MasterClass.objects.prefetch_related('participants').all():
        if master_class.finance_transaction_id:
            transaction = FinanceTransaction.objects.filter(pk=master_class.finance_transaction_id).first()
            if transaction and transaction.amount > 0 and not MasterClassPayment.objects.filter(finance_transaction_id=transaction.id).exists():
                MasterClassPayment.objects.create(
                    master_class_id=master_class.id,
                    payment_type='legacy',
                    amount=money(transaction.amount),
                    payment_date=master_class.payment_date or local_date(transaction.paid_at) or django.utils.timezone.localdate(),
                    accepted_by_id=transaction.created_by_id,
                    finance_transaction_id=transaction.id,
                    comment=master_class.description or '',
                )
        elif master_class.payment_amount and master_class.payment_amount > 0 and not MasterClassPayment.objects.filter(master_class_id=master_class.id).exists():
            client = master_class.participants.first()
            payment_date = master_class.payment_date or django.utils.timezone.localdate()
            transaction = FinanceTransaction.objects.create(
                branch_id=master_class.branch_id,
                transaction_type='income',
                amount=money(master_class.payment_amount),
                source='master_class',
                subtotal_amount=money(master_class.payment_amount),
                client_id=client.id if client else None,
                manager_id=master_class.manager_id,
                paid_at=paid_at_from_date(payment_date),
                comment=f'Legacy master class payment: {master_class.title}',
            )
            MasterClassPayment.objects.create(
                master_class_id=master_class.id,
                payment_type='legacy',
                amount=money(master_class.payment_amount),
                payment_date=payment_date,
                accepted_by_id=None,
                finance_transaction_id=transaction.id,
                comment=master_class.description or '',
            )

        payments = list(
            MasterClassPayment.objects
            .filter(master_class_id=master_class.id)
            .order_by('payment_date', 'created_at', 'id')
        )
        if payments:
            MasterClass.objects.filter(pk=master_class.id).update(
                payment_amount=money(sum((payment.amount for payment in payments), Decimal('0.00'))),
                payment_date=payments[-1].payment_date,
                finance_transaction_id=payments[-1].finance_transaction_id,
            )


def unmigrate_master_class_payments(apps, schema_editor):
    MasterClassPayment = apps.get_model('crm', 'MasterClassPayment')
    MasterClassPayment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_masterclassstaffassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterClassPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('prepayment', 'Prepayment'), ('additional', 'Additional'), ('legacy', 'Legacy')], default='additional', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('comment', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_master_class_payments', to=settings.AUTH_USER_MODEL)),
                ('finance_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_class_payment_entry', to='crm.financetransaction')),
                ('master_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.masterclass')),
            ],
            options={
                'ordering': ('payment_date', 'created_at', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='master_class_payment_amount_positive')],
            },
        ),
        migrations.RunPython(migrate_master_class_payments, unmigrate_master_class_payments),
    ]
