# Generated by Django 6.0.6 on 2026-09-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_businessmediaasset_catalogitemimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('import', 'Import'), ('payment', 'Payment'), ('visit', 'Visit'), ('task_done', 'Task done'), ('password_change', 'Password change'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('trial_converted_to_subscription', 'Trial converted to subscription'), ('catalog_item_create', 'Catalog item create'), ('catalog_item_update', 'Catalog item update'), ('catalog_item_disable', 'Catalog item disable'), ('branch_create', 'Branch create'), ('branch_update', 'Branch update'), ('branch_disable', 'Branch disable'), ('payment_method_create', 'Payment method create'), ('payment_method_update', 'Payment method update'), ('payment_method_disable', 'Payment method disable'), ('payment_method_enable', 'Payment method enable'), ('discount_create', 'Discount create'), ('discount_update', 'Discount update'), ('discount_disable', 'Discount disable'), ('discount_enable', 'Discount enable'), ('group_update', 'Group update'), ('group_disable', 'Group disable'), ('group_enable', 'Group enable'), ('group_member_add', 'Group member add'), ('group_member_remove', 'Group member remove'), ('group_member_restore', 'Group member restore'), ('addon_sale_create', 'Addon sale create'), ('addon_sale_update', 'Addon sale update'), ('cash_reconciliation', 'Cash reconciliation'), ('employee_schedule_create', 'Employee schedule create'), ('employee_schedule_update', 'Employee schedule update'), ('payroll_profile_update', 'Payroll profile update'), ('payroll_generate', 'Payroll generate'), ('payroll_recalculate', 'Payroll recalculate'), ('payroll_adjust', 'Payroll adjust'), ('payroll_approve', 'Payroll approve'), ('payroll_paid', 'Payroll paid'), ('finance_manager_update', 'Finance manager update'), ('master_class_duration_update', 'Master class duration update'), ('certificate_template_create', 'Certificate template create'), ('certificate_template_update', 'Certificate template update'), ('certificate_template_disable', 'Certificate template disable'), ('certificate_create', 'Certificate create'), ('certificate_update', 'Certificate update'), ('certificate_redeem', 'Certificate redeem'), ('certificate_cancel', 'Certificate cancel'), ('certificate_whatsapp_open', 'Certificate WhatsApp open'), ('certificate_batch_create', 'Certificate batch create'), ('certificate_asset_upload', 'Certificate asset upload'), ('certificate_visit_create', 'Certificate visit create'), ('messaging_channel_create', 'Messaging channel create'), ('messaging_channel_update', 'Messaging channel update'), ('lead_created_from_message', 'Lead created from message'), ('lead_status_update', 'Lead status update'), ('lead_assign', 'Lead assign'), ('lead_link_client', 'Lead link client'), ('lead_create_client', 'Lead create client'), ('lead_convert_to_trial', 'Lead convert to trial'), ('lead_mark_read', 'Lead mark read'), ('meta_webhook_error', 'Meta webhook error'), ('client_merge', 'Client merge')], max_length=50),
        ),
    ]
