# Generated by Django 6.0.6 on 2026-09-13 15:23

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), name='unique_master_class_subject_normalized_name')],
            },
        ),
        migrations.AddField(
            model_name='masterclass',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_classes', to='crm.masterclasssubject'),
        ),
    ]
