# Generated by Django 6.0.6 on 2026-09-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_masterclasssubject_masterclass_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonsaleitem',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
