# Generated by Django 6.0.6 on 2026-09-15 14:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_payroll_profiles_to_rules(apps, schema_editor):
    EmployeePayrollProfile = apps.get_model('crm', 'EmployeePayrollProfile')
    EmployeePayrollRule = apps.get_model('crm', 'EmployeePayrollRule')
    PayrollStatement = apps.get_model('crm', 'PayrollStatement')
    today = django.utils.timezone.localdate()

    for profile in EmployeePayrollProfile.objects.using(schema_editor.connection.alias).all().iterator():
        existing = EmployeePayrollRule.objects.using(schema_editor.connection.alias).filter(profile=profile)
        if existing.exists():
            continue
        rules = []
        if profile.pay_type == 'monthly' and profile.monthly_salary:
            rules.append(EmployeePayrollRule(profile=profile, rule_type='monthly_salary', amount=profile.monthly_salary, valid_from=today))
        if profile.pay_type == 'hourly' and profile.regular_hourly_rate:
            rules.append(EmployeePayrollRule(profile=profile, rule_type='regular_hourly', amount=profile.regular_hourly_rate, valid_from=today))
        if profile.outside_hourly_rate:
            rules.append(EmployeePayrollRule(profile=profile, rule_type='outside_hourly', amount=profile.outside_hourly_rate, valid_from=today))
        if profile.outside_master_class_bonus:
            rules.append(EmployeePayrollRule(profile=profile, rule_type='outside_master_class_bonus', amount=profile.outside_master_class_bonus, valid_from=today))
        if rules:
            EmployeePayrollRule.objects.using(schema_editor.connection.alias).bulk_create(rules)

    PayrollStatement.objects.using(schema_editor.connection.alias).filter(gross_amount=0, amount_to_pay=0).update(
        gross_amount=models.F('total_amount'),
        amount_to_pay=models.F('total_amount'),
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_sync_trial_finance_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollstatement',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollstatement',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollstatement',
            name='calculation_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payrollstatement',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollstatement',
            name='lesson_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollstatement',
            name='lesson_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollstatement',
            name='payroll_rules_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='payrollstatement',
            name='sales_basis_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollstatement',
            name='sales_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollstatement',
            name='sales_transactions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollstatement',
            name='shift_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollstatement',
            name='shift_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EmployeePayrollAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance_date', models.DateField(default=django.utils.timezone.localdate)),
                ('comment', models.TextField(blank=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_advances', to='crm.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_advances', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_advances', to=settings.AUTH_USER_MODEL)),
                ('finance_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_advance', to='crm.financetransaction')),
            ],
            options={
                'ordering': ('advance_date', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EmployeePayrollRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('monthly_salary', 'Оклад'), ('shift_rate', 'Оплата за смену'), ('lesson_rate', 'Оплата за занятие'), ('regular_hourly', 'Почасовая ставка'), ('outside_hourly', 'Работа вне графика'), ('outside_master_class_bonus', 'Доплата за МК вне графика'), ('sales_percent', 'Процент от продаж')], max_length=40)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('percent', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('sales_sources', models.JSONField(blank=True, default=list)),
                ('sales_attribution', models.CharField(choices=[('responsible_manager', 'Ответственный менеджер'), ('created_by', 'Создатель операции')], default='responsible_manager', max_length=40)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='crm.employeepayrollprofile')),
            ],
            options={
                'ordering': ('profile__employee__first_name', 'profile__employee__username', 'rule_type', '-valid_from', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PayrollAdvanceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='crm.employeepayrolladvance')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_allocations', to='crm.payrollstatement')),
            ],
            options={
                'ordering': ('advance__advance_date', 'advance_id'),
            },
        ),
        migrations.AddConstraint(
            model_name='employeepayrolladvance',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payroll_advance_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='employeepayrollrule',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='payroll_rule_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='employeepayrollrule',
            constraint=models.CheckConstraint(condition=models.Q(('percent__isnull', True), models.Q(('percent__gte', 0), ('percent__lte', 100)), _connector='OR'), name='payroll_rule_percent_between_0_100'),
        ),
        migrations.AddConstraint(
            model_name='payrolladvanceallocation',
            constraint=models.UniqueConstraint(fields=('statement', 'advance'), name='unique_payroll_advance_allocation'),
        ),
        migrations.AddConstraint(
            model_name='payrolladvanceallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payroll_advance_allocation_amount_positive'),
        ),
        migrations.RunPython(migrate_payroll_profiles_to_rules, noop_reverse),
    ]
