# Generated by Django 6.0.6 on 2026-09-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_payrollstatement_advance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollstatement',
            name='lesson_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollstatement',
            name='lesson_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollstatement',
            name='shift_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollstatement',
            name='shift_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeepayrollrule',
            name='rule_type',
            field=models.CharField(choices=[('monthly_salary', 'Оклад'), ('shift_rate', 'Оплата за смену'), ('lesson_rate', 'Оплата за занятие'), ('regular_hourly', 'Почасовая ставка'), ('outside_hourly', 'Работа вне графика'), ('outside_master_class_bonus', 'Доплата за МК вне графика'), ('sales_percent', 'Процент от продаж')], max_length=40),
        ),
    ]
