# Generated by Django 6.0.6 on 2026-10-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_employeeshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='relatives',
            field=models.ManyToManyField(blank=True, to='crm.client'),
        ),
    ]
