# Generated by Django 6.0.6 on 2026-07-05 20:05

from django.db import migrations, models


def backfill_roles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        roles = user.roles if isinstance(user.roles, list) else []
        if roles:
            continue
        if user.role:
            user.roles = [user.role]
        elif user.is_superuser:
            user.role = 'admin'
            user.roles = ['admin']
        else:
            user.roles = []
        user.save(update_fields=['role', 'roles'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill_roles, migrations.RunPython.noop),
    ]
