# Generated by Django 6.0.6 on 2026-07-09 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_branch_alter_auditlog_action_client_branch_and_more'),
        ('users', '0003_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='crm.branch'),
        ),
    ]
