# Generated by Django 6.0.6 on 2026-09-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_delete_settings',
            field=models.BooleanField(default=False),
        ),
    ]
